simulate failed deployments

diff --git a/.github/actions/deploy_eks/action.yml b/.github/actions/deploy_eks/action.yml
--- a/.github/actions/deploy_eks/action.yml
+++ b/.github/actions/deploy_eks/action.yml
@@ -41,16 +41,23 @@ runs:
       shell: bash
       # env:
       run: |
-        if [[ ${{ inputs.release }} == "scripts" ]]
-        then
-          echo "Deploy scripts with v1"
+        if (( $RANDOM % 2 == 0 )); then
+          echo "Simulated Failure"
+          exit 1
         else
-          # adding comments testing
-          echo "Deploy Helm Chat with Below Values"
-          echo "Chart path: ${{ inputs.chart }}"
-          echo "Namespace: ${{ inputs.namespace }}"
-          echo "Commit ID: ${{ inputs.tag }}"
-          echo "Value File Path: ${{ inputs.valuefile }}"
-          echo "Release name: ${{ inputs.release }}"
-          echo "AWS Secret: $AWS_SECRET"
+          echo "Continuing with normal execution simulation"
+          sleep 60
         fi
+        # if [[ ${{ inputs.release }} == "scripts" ]]
+        # then
+        #   echo "Deploy scripts with v1"
+        # else
+        #   # adding comments testing
+        #   echo "Deploy Helm Chat with Below Values"
+        #   echo "Chart path: ${{ inputs.chart }}"
+        #   echo "Namespace: ${{ inputs.namespace }}"
+        #   echo "Commit ID: ${{ inputs.tag }}"
+        #   echo "Value File Path: ${{ inputs.valuefile }}"
+        #   echo "Release name: ${{ inputs.release }}"
+        #   echo "AWS Secret: $AWS_SECRET"
+        # fi
